version: '3.8'
services:

  localstack:
    image: localstack/localstack:0.12.6
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=s3,sns
      - DEBUG=0
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './services/localstack:/docker-entrypoint-initaws.d'
    networks:
      - micro-hero
    healthcheck:
      test: awslocal --version
      interval: 10s
      timeout: 10s
    restart: always

  visit:
    image: micro-hero/visit
    build: ./services/visit
    env_file:
      aws.env
    depends_on:
      localstack:
        condition: service_healthy
      recognize:
        condition: service_started
      detect:
        condition: service_started
    networks:
      - micro-hero
    logging:
      driver: local

  detect:
    image: micro-hero/detect
    build: ./services/detect
    env_file:
      aws.env
    environment:
      - PORT=3001
    depends_on:
      localstack:
        condition: service_healthy
      recognize:
        condition: service_started
    networks:
      - micro-hero
    logging:
      driver: local

  recognize:
    image: micro-hero/recognize
    build: ./services/recognize
    ports:
      - '5000:5000'
    env_file:
      aws.env
    environment:
      - BATMAN_IMG=/usr/src/app/batman.jpg
      - RECOGNIZE_ENDPOINT=http://recognize:5000/sns
    depends_on:
      localstack:
        condition: service_healthy
    networks:
      - micro-hero
    logging:
      driver: local

networks:
  micro-hero:
    driver: bridge